---
apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s1
  namespace: hello
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: hello-k8s1
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: hello
  name: hello-k8s1
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: hello1.fiture.us
      http:
        paths:
          - path: /
            backend:
              serviceName: hello
              servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello
  name: hello-k8s1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-k8s1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-k8s1
    spec:
      containers:
        - name: hello-k8s1
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
